# Site settings
title:          HYUNSOO'S TECH BLOG
description:    "현수의 기술 블로그"
url:            "https://hyunsooo.github.io"

# Author
author:
  name:         Hyunsoo Han
  url:          https://github.com/hyunsooo
  email:        hyunsooo__@naver.com

# Build settings
  markdown:       kramdown

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-paginate
  # - jemoji #Uncomment this to allow emoji in your post

# Permalinks
permalink:      /:year-:month-:day/:title
paginate:       5
